#include "cdough.h"

using namespace cdough::debug;
using namespace cdough::service;
using namespace COMPILED_MPC_PROTOCOL_NAMESPACE;

const int test_size = 1 << 14;
const int DIV_TEST_SIZE = 1 << 6;

template <typename T, typename Engine>
void test_b2a_bit(int test_size, Engine& engine) {
    cdough::Vector<T> v(test_size);
    engine.populateLocalRandom(v);

    // all parties will agree on the random vector generated by party 0
    BSharedVector<T> b = engine.secret_share_b(v, 0);
    b.mask(1);

    // perform the conversion
    ASharedVector<T> a = b.b2a_bit();

    // check that the binary and arithmetic openings are the same
    auto a_opened = a.open();
    auto b_opened = b.open();
    assert(a_opened.same_as(b_opened));
}

template <typename T, typename Engine>
void test_b2a(int test_size, Engine& engine) {
    cdough::Vector<T> v(test_size);
    engine.populateLocalRandom(v);

    BSharedVector<T> b = engine.secret_share_b(v, 0);
    ASharedVector<T> a = b.b2a();

    auto a_opened = a.open();
    auto b_opened = b.open();

    for (int i = 0; i < test_size; i++) {
        assert(a_opened[i] == b_opened[i]);
    }
}

// Define a test for secret-vs-plaintext binary operators
#define DEFINE_TEST_BINARY_OP(_op_, shareType, name)                   \
    template <typename T, typename Engine>                             \
    void test_##name(int test_size, Engine& engine) {                  \
        auto L = std::numeric_limits<std::make_unsigned_t<T>>::digits; \
        single_cout_nonl(L << "-bit " #name "... ");                   \
        cdough::Vector<T> x(test_size);                                   \
        cdough::Vector<T> y(test_size);                                   \
                                                                       \
        if (engine.getPartyID() == 0) {                                \
            engine.populateLocalRandom(x);                             \
            engine.populateLocalRandom(y);                             \
        }                                                              \
                                                                       \
        shareType<T> sx(test_size, engine);                            \
        shareType<T> sy(test_size, engine);                            \
        secret_share_vec(x, sx);                                       \
        secret_share_vec(y, sy);                                       \
                                                                       \
        auto sz = sx _op_ sy;                                          \
                                                                       \
        auto z1 = sz->open();                                          \
        auto z2 = x _op_ y;                                            \
                                                                       \
        if (engine.getPartyID() == 0) {                                \
            assert(z1.same_as(z2));                                    \
            single_cout("OK");                                         \
        }                                                              \
    }

DEFINE_TEST_BINARY_OP(*, ASharedVector, multiplication);
DEFINE_TEST_BINARY_OP(>, ASharedVector, arithmetic_greater_than);
DEFINE_TEST_BINARY_OP(>=, ASharedVector, arithmetic_greater_than_equal);
DEFINE_TEST_BINARY_OP(==, ASharedVector, arithmetic_equal);
DEFINE_TEST_BINARY_OP(+, BSharedVector, binary_add);
DEFINE_TEST_BINARY_OP(-, BSharedVector, binary_subtract);
DEFINE_TEST_BINARY_OP(&, BSharedVector, and);
DEFINE_TEST_BINARY_OP(^, BSharedVector, xor);
DEFINE_TEST_BINARY_OP(|, BSharedVector, or);
DEFINE_TEST_BINARY_OP(>, BSharedVector, greater_than);
DEFINE_TEST_BINARY_OP(<, BSharedVector, less_than);

template <typename T, typename Engine>
void test_private_division(int test_size, Engine& engine) {
    using uT = std::make_unsigned_t<T>;
    auto L = std::numeric_limits<uT>::digits;
    single_cout_nonl("Boolean long division, " << L << "-bit... ");

    auto m = static_cast<double>(std::numeric_limits<T>::max());
    auto scale = static_cast<T>(sqrt(m));

    // Generate reasonable division test values
    Vector<uT> ub(test_size);
    engine.populateLocalRandom(ub);
    ub = (ub % (scale - 1)) + 1;
    Vector<uT> q(test_size);
    engine.populateLocalRandom(q);
    q = (q % (scale - 1)) + 1;

    Vector<T> b(test_size);
    b = ub;

    Vector<T> a(test_size);
    a = ub * q;

    auto truth = a / b;

    BSharedVector<T> a_ = engine.secret_share_b(a, 0);
    BSharedVector<T> b_ = engine.secret_share_b(b, 0);
    auto d = a_ / b_;
    auto opened = d->open();

    if (engine.getPartyID() == 0) {
        assert(opened.same_as(truth));
    }

    single_cout("OK");
}

template <typename T, typename Engine>
void test_dot_product(int test_size, const size_t aggSize, Engine& engine) {
    auto L = std::numeric_limits<std::make_unsigned_t<T>>::digits;
    single_cout_nonl(L << "-bit dot product(" << aggSize << ")... ");

    if (test_size % aggSize != 0) {
        test_size *= aggSize;
    }

    cdough::Vector<T> x(test_size), y(test_size);

    if (engine.getPartyID() == 0) {
        engine.populateLocalRandom(x);
        engine.populateLocalRandom(y);
    }

    ASharedVector<T> sx = engine.secret_share_a(x, 0);
    ASharedVector<T> sy = engine.secret_share_a(y, 0);

    auto sz = sx.dot_product(sy, aggSize);
    auto z1 = sz->open();
    auto z2 = x.dot_product(y, aggSize);

    if (engine.getPartyID() == 0) {
        assert(z1.same_as(z2));
        single_cout("OK");
    }
}

template <typename T, typename Engine>
void test_equals(int test_size, Engine& engine) {
    auto L = std::numeric_limits<std::make_unsigned_t<T>>::digits;
    single_cout_nonl(L << "-bit equals...");
    cdough::Vector<T> x(test_size), y(test_size);

    if (engine.getPartyID() == 0) {
        engine.populateLocalRandom(x);
        engine.populateLocalRandom(y);
        y %= 3;
        y += x;
    }

    BSharedVector<T> sx = engine.secret_share_b(x, 0);
    BSharedVector<T> sy = engine.secret_share_b(y, 0);

    auto sz = sx == sy;
    auto z1 = sz->open();
    auto z2 = x == y;
    if (engine.getPartyID() == 0) {
        assert(z1.same_as(z2));
        single_cout("OK");
    }
}

template <typename T, typename Engine>
void test_arithmetic_greater_than_public(Vector<T> data, Engine& engine) {
    ASharedVector<int> a_s = engine.secret_share_a(data, 0);
    ASharedVector<int> res = a_s.gtez();
    auto expected = (data >= 0);

    auto z = res.open();

    assert(z.same_as(expected));
    single_cout("Arithmetic >= " << 0 << " OK");
}

int main(int argc, char** argv) {
    EngineRef engine = cdough_init(argc, argv);

#if defined(USE_LIBOTE) && !defined(GITHUB_ACTIONS)
    // Approximate values for default 16k test, just so it doesn't take forever.
    // Scaling may not be perfect for other test sizes.
    // Don't do this on the CI -- we run out of memory
    stopwatch::timepoint("Start Preprocessing...");
    engine.reserve_mul_triples<int8_t>(test_size * 10);
    engine.reserve_and_triples<int8_t>(test_size * 32);
    stopwatch::timepoint("Reserve i8");
    engine.reserve_mul_triples<int16_t>(test_size * 8);
    engine.reserve_and_triples<int16_t>(test_size);
    stopwatch::timepoint("Reserve i16");
    engine.reserve_mul_triples<int32_t>(test_size * 10);
    engine.reserve_and_triples<int32_t>(test_size * 44);
    stopwatch::timepoint("Reserve i32");
    engine.reserve_mul_triples<int64_t>(test_size * 10);
    engine.reserve_and_triples<int64_t>(test_size * 50);
    stopwatch::timepoint("Reserve i64");
    engine.reserve_mul_triples<__int128_t>(test_size * 10);
    engine.reserve_and_triples<__int128_t>(test_size * 57);
    stopwatch::timepoint("Reserve i128");

    std::cout << "Done preprocessing.\n";
#endif

    // The party's unique id
    auto pID = engine.getPartyID();

    // Input plaintext data for testing secure comparisons
    cdough::Vector<int> data_a = {111, -4, -17, 2345, 999, 0, -28922, 1231241, 0, -23437};
    cdough::Vector<int> data_b = {0, -4, -5, -123556, 999, 70, -243242, INT_MAX, 0, 78};

    assert(data_a.size() == data_b.size());

    // **************************************** //
    //           Basic Secret Sharing           //
    // **************************************** //

    {
        ASharedVector<int> a_v1 = engine.secret_share_a(data_a, 0);
        assert(a_v1.open().same_as(data_a));
        single_cout("Arithmetic Secret sharing... OK");
    }

    {
        BSharedVector<int> b_v1 = engine.secret_share_b(data_a, 0);
        assert(b_v1.open().same_as(data_a));
        single_cout("Boolean Secret sharing... OK");
    }

    // **************************************** //
    //           Arithmetic primitives          //
    // **************************************** //
    ASharedVector<int> a_v1 = engine.secret_share_a(data_a, 0);
    ASharedVector<int> a_v2 = engine.secret_share_a(data_b, 0);

    // Apply elementwise secure addition
    ASharedVector<int> c_add = a_v1 + a_v2;
    // Open added numbers
    auto c_add_open = c_add.open();
    // Get ground truth
    cdough::Vector<int> sum = (data_a + data_b);
    // Compare sums with ground truth
    assert(c_add_open.same_as(sum));

    if (pID == 0) std::cout << "Addition...OK" << std::endl;

    {
        ASharedVector<int> a_s = engine.secret_share_a(data_a, 0);
        ASharedVector<int> b_s = engine.secret_share_a(data_b, 0);

        a_s += b_s;

        assert(a_s.open().same_as(data_a + data_b));
        single_cout("Increment += OK");
    }

    // Apply elementwise secure addition
    ASharedVector<int> c_sub = a_v1 - a_v2;
    // Open added numbers
    auto c_sub_open = c_sub.open();
    // Get ground truth
    cdough::Vector<int> sub = (data_a - data_b);
    // Compare diffs with ground truth
    assert(c_sub_open.same_as(sub));

    if (pID == 0) std::cout << "Subtraction...OK" << std::endl;

    {
        ASharedVector<int> a_s = engine.secret_share_a(data_a, 0);
        ASharedVector<int> b_s = engine.secret_share_a(data_b, 0);

        a_s -= b_s;

        assert(a_s.open().same_as(data_a - data_b));
        single_cout("Decrement -= OK");
    }

    test_multiplication<int8_t>(test_size, engine);
    test_multiplication<int32_t>(test_size, engine);
    test_multiplication<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_multiplication<__int128_t>(test_size, engine);
#else
    single_cout("MPC_PROTOCOL_SPDZ_2K_NPC is defined. Skipping test_multiplication<__int128_t>.");
#endif

    test_arithmetic_greater_than_public<int32_t>(data_a, engine);

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_arithmetic_greater_than<int8_t>(test_size, engine);
    test_arithmetic_greater_than<int32_t>(test_size, engine);
    test_arithmetic_greater_than<int64_t>(test_size, engine);
    test_arithmetic_greater_than<__int128_t>(test_size, engine);

    test_arithmetic_greater_than_equal<int8_t>(test_size, engine);
    test_arithmetic_greater_than_equal<int32_t>(test_size, engine);
    test_arithmetic_greater_than_equal<int64_t>(test_size, engine);
    test_arithmetic_greater_than_equal<__int128_t>(test_size, engine);

    test_arithmetic_equal<int8_t>(test_size, engine);
    test_arithmetic_equal<int32_t>(test_size, engine);
    test_arithmetic_equal<int64_t>(test_size, engine);
    test_arithmetic_equal<__int128_t>(test_size, engine);
#else
    single_cout("MPC_PROTOCOL_SPDZ_2K_NPC is defined. Skipping ASecretShared comparisons.");
#endif

    engine.malicious_check();

    {
        ASharedVector<int> a_s = engine.secret_share_a(data_a, 0);
        ASharedVector<int> b_s = engine.secret_share_a(data_b, 0);

        a_s *= b_s;

        assert(a_s.open().same_as(data_a * data_b));
        single_cout("Multiply Assignment *= OK");
    }

    {
        // TODO: check overflowing when dividing INT_MAX in fantastic four
        // cdough::Vector<int> div_data = {111, 1231241, 999, 109, 0, -4, -17, 2345,   -28922, -23437};
        // cdough::Vector<int> div_data = {0, -4, -5, -123556, 999, 70, -243242, INT_MAX, 0, 78};
        cdough::Vector<int64_t> div_data = {0,      4,           5,       123556, 999, 70,
                                         243242, INT_MAX - 1, INT_MAX, 0,      78};
        ASharedVector<int64_t> shared_div_data = engine.secret_share_a(div_data, 0);

        // Apply elementwise secure public constant division
        ASharedVector<int64_t> c_div = shared_div_data / 8;

#ifdef MPC_PROTOCOL_REPLICATED_THREE
        // check for large truncation error
        int count_truncation_errors = 0;
        if (pID == 0) {
            // get the other share from party 2
            cdough::Vector<int64_t> my_share = c_div.asContainer()(0);
            cdough::Vector<int64_t> other_share(div_data.size());
            engine.comm0()->receiveShares(other_share, +2);
            for (int i = 0; i < div_data.size(); i++) {
                int sign_x = (div_data[i] >= 0);
                int sign_x1 = (my_share[i] >= 0);
                int sign_x2 = (other_share[i] >= 0);
                if ((sign_x1 == sign_x2) && (sign_x1 != sign_x)) {
                    count_truncation_errors++;
                }
            }
            // send number of truncation errors
            engine.comm0()->sendShare(count_truncation_errors, +1);
            engine.comm0()->sendShare(count_truncation_errors, +2);
        } else if (pID == 2) {
            // send first share to party 0
            engine.comm0()->sendShares(c_div.asContainer()(0), +1);
            // receive number of truncation errors
            engine.comm0()->receiveShare(count_truncation_errors, +1);
        } else if (pID == 1) {
            // receive number of truncation errors
            engine.comm0()->receiveShare(count_truncation_errors, +2);
        }

        // Open divided numbers
        auto c_div_open = c_div.open();
        // Get ground truth
        cdough::Vector<int64_t> div = div_data / 8;
        // Compare division results with ground truth
        if (count_truncation_errors > 0) {
            if (pID == 0)
                std::cout << "WARNING: large truncation error occurred, skipping correctness check"
                          << std::endl;
        } else {
            assert(c_div_open.same_as(div));
        }
#else  // Other protocols: no truncation check
       // Open divided numbers
        auto c_div_open = c_div.open();
        // Get ground truth
        cdough::Vector<int64_t> div = div_data / 8;
        // Compare division results with ground truth

        assert(c_div_open.same_as(div));
#endif
        if (pID == 0) std::cout << "Public Constant Division...OK" << std::endl;
    }

    // Apply elementwise secure arithmetic negation
    ASharedVector<int> c_a_neg = -a_v1;
    // Open added numbers
    auto c_a_neg_open = c_a_neg.open();
    // Get ground truth
    cdough::Vector<int> a_neg = -data_a;
    // Compare negated elements with ground truth
    assert(c_a_neg_open.same_as(a_neg));

    if (pID == 0) std::cout << "Arithmetic negation...OK" << std::endl;

    // Test dot product
    test_dot_product<int8_t>(test_size, 7, engine);
    test_dot_product<int8_t>(test_size, test_size, engine);
    test_dot_product<int16_t>(test_size, 7, engine);
    test_dot_product<int16_t>(test_size, test_size, engine);
    test_dot_product<int32_t>(test_size, 7, engine);
    test_dot_product<int32_t>(test_size, test_size, engine);
    test_dot_product<int64_t>(test_size, 7, engine);
    test_dot_product<int64_t>(test_size, test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_dot_product<__int128_t>(test_size, 7, engine);
    test_dot_product<__int128_t>(test_size, test_size, engine);
#else
    single_cout("MPC_PROTOCOL_SPDZ_2K_NPC is defined. Skipping test_dot_product<__int128_t>.");
#endif

    // **************************************** //
    //             Boolean primitives           //
    // **************************************** //

    // Secret-share original vectors using boolean sharing
    BSharedVector<int> b_v1 = engine.secret_share_b(data_a, 0);
    BSharedVector<int> b_v2 = engine.secret_share_b(data_b, 0);
    
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_and<int8_t>(test_size, engine);
    test_and<int32_t>(test_size, engine);
    test_and<int64_t>(test_size, engine);
    test_and<__int128_t>(test_size, engine);

    {
        BSharedVector<int> a_s = engine.secret_share_b(data_a, 0);
        BSharedVector<int> b_s = engine.secret_share_b(data_b, 0);

        a_s &= b_s;

        assert(a_s.open().same_as(data_a & data_b));
        single_cout("Bitwise &= OK");
    }

    {
        BSharedVector<int> a_s = engine.secret_share_b(data_a, 0);
        BSharedVector<int> b_s = engine.secret_share_b(data_b, 0);

        a_s |= b_s;

        assert(a_s.open().same_as(data_a | data_b));
        single_cout("Bitwise |= OK");
    }

    {
        BSharedVector<int> a_s = engine.secret_share_b(data_a, 0);
        BSharedVector<int> b_s = engine.secret_share_b(data_b, 0);

        a_s ^= b_s;

        assert(a_s.open().same_as(data_a ^ data_b));
        single_cout("Bitwise ^= OK");
    }

    test_xor<int8_t>(test_size, engine);
    test_xor<int32_t>(test_size, engine);
    test_xor<int64_t>(test_size, engine);
    test_xor<__int128_t>(test_size, engine);

    test_or<int8_t>(test_size, engine);
    test_or<int32_t>(test_size, engine);
    test_or<int64_t>(test_size, engine);
    test_or<__int128_t>(test_size, engine);
#endif

    test_equals<int8_t>(test_size, engine);
    test_equals<int32_t>(test_size, engine);
    test_equals<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_equals<__int128_t>(test_size, engine);
#endif

    test_greater_than<int8_t>(test_size, engine);
    test_greater_than<int32_t>(test_size, engine);
    test_greater_than<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_greater_than<__int128_t>(test_size, engine);
#endif

    test_less_than<int8_t>(test_size, engine);
    test_less_than<int32_t>(test_size, engine);
    test_less_than<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_less_than<__int128_t>(test_size, engine);
#endif
    // Apply elementwise secure boolean negation
    BSharedVector<int> c_b_neg = !(b_v1 == b_v2);
    // Open NOT results
    auto c_b_neg_open = c_b_neg.open();
    // Get ground truth
    cdough::Vector<int> a_b_neg = !(data_a == data_b);

    // Compare NOT results with ground truth
    assert(c_b_neg_open.same_as(a_b_neg));

    if (pID == 0) std::cout << "Boolean NOT...OK" << std::endl;

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    // Apply elementwise secure boolean negation
    BSharedVector<int> c_b_comp = ~b_v1;
    // Open NOT results
    auto c_b_comp_open = c_b_comp.open();
    // Get ground truth
    cdough::Vector<int> a_b_comp = ~data_a;

    // Compare NOT results with ground truth
    assert(c_b_comp_open.same_as(a_b_comp));

    if (pID == 0) std::cout << "Boolean complement...OK" << std::endl;
#endif

    // Apply elementwise secure boolean addition with PPA
    BSharedVector<int> c_b_add_ppa = b_v1.ppa(b_v2);
    // Open addition results
    auto c_b_add_ppa_open = c_b_add_ppa.open();
    // Get ground truth
    cdough::Vector<int> a_b_add = data_a + data_b;

    // Compare addition results with ground truth
    assert(c_b_add_ppa_open.same_as(a_b_add));
    if (pID == 0) std::cout << "Parallel prefix adder...OK" << std::endl;

    test_binary_add<int8_t>(test_size, engine);
    test_binary_add<int32_t>(test_size, engine);
    test_binary_add<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_binary_add<__int128_t>(test_size, engine);
#endif

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_binary_subtract<int8_t>(test_size, engine);
    test_binary_subtract<int32_t>(test_size, engine);
    test_binary_subtract<int64_t>(test_size, engine);
    test_binary_subtract<__int128_t>(test_size, engine);
#endif

    // ...with carry in
    auto c_b_add_rca = b_v1.rca(b_v2, true);
    auto c_b_add_rca_open = c_b_add_rca->open();
    assert(c_b_add_rca_open.same_as(a_b_add + 1));
    if (pID == 0) std::cout << "RCA carry in...OK" << std::endl;

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    // ...subtraction
    auto c_b_sub_rca = b_v1 - b_v2;
    auto c_b_sub_rca_open = c_b_sub_rca->open();
    assert(c_b_sub_rca_open.same_as(data_a - data_b));
    if (pID == 0) std::cout << "RCA subtraction...OK" << std::endl;

    // ...compare
    {
        auto rca_cmp = b_v1.rca_compare(b_v2);
        auto opened = rca_cmp->open();
        assert(opened.same_as(data_a < data_b));
        single_cout("RCA cmp... OK");
    }

    // Test ripple_carry_adder_packed_sign
    {
        auto c_b_add_rca_packed = b_v1.rca_packed_sign(b_v2, false);
        auto c_b_add_rca_packed_open = c_b_add_rca_packed->open();

        // Unpack the result
        cdough::Vector<int> c_b_add_rca_packed_unpacked(data_a.size());
        c_b_add_rca_packed_unpacked.unpack_from(c_b_add_rca_packed_open, 0);

        assert(c_b_add_rca_packed_unpacked.same_as((data_a + data_b) < 0));
        if (pID == 0) std::cout << "RCA packed sign addition...OK" << std::endl;
    }

    // Test ripple_carry_adder_packed_sign with carry in
    {
        auto c_b_add_rca_packed_carry = b_v1.rca_packed_sign(b_v2, true);
        auto c_b_add_rca_packed_carry_open = c_b_add_rca_packed_carry->open();

        // Unpack the result
        cdough::Vector<int> c_b_add_rca_packed_carry_unpacked(data_a.size());
        c_b_add_rca_packed_carry_unpacked.unpack_from(c_b_add_rca_packed_carry_open, 0);

        assert(c_b_add_rca_packed_carry_unpacked.same_as((data_a + data_b + 1) < 0));
        if (pID == 0) std::cout << "RCA packed sign addition with carry...OK" << std::endl;
    }
#endif

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    // Private Division
    test_private_division<int8_t>(DIV_TEST_SIZE, engine);
    test_private_division<int32_t>(DIV_TEST_SIZE, engine);
    test_private_division<int64_t>(DIV_TEST_SIZE, engine);
#endif

    // **************************************** //
    //             Other primitives             //
    // **************************************** //

    BSharedVector<int> a2b1 = a_v1.a2b();
    BSharedVector<int> a2b2 = a_v2.a2b();

    auto a2b1_open = a2b1.open();
    auto a2b2_open = a2b2.open();

    assert(a2b1_open.same_as(data_a));
    assert(a2b2_open.same_as(data_b));

    if (pID == 0) std::cout << "Arithmetic to boolean conversion...OK" << std::endl;

#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    BSharedVector<int> a2b1_sign = a_v1.a2b_packed_sign();
    BSharedVector<int> a2b2_sign = a_v2.a2b_packed_sign();

    auto a2b1_sign_open = a2b1_sign.open();
    auto a2b2_sign_open = a2b2_sign.open();

    cdough::Vector<int> a2b1_sign_open_unpacked(a_v1.size());
    cdough::Vector<int> a2b2_sign_open_unpacked(a_v2.size());

    a2b1_sign_open_unpacked.unpack_from(a2b1_sign_open, 0);
    a2b2_sign_open_unpacked.unpack_from(a2b2_sign_open, 0);

    assert(a2b1_sign_open_unpacked.same_as((data_a < 0)));
    assert(a2b2_sign_open_unpacked.same_as((data_b < 0)));
    if (pID == 0) std::cout << "Arithmetic to boolean sign conversion...OK" << std::endl;
#endif

    test_b2a_bit<int8_t>(test_size, engine);
    test_b2a_bit<int32_t>(test_size, engine);
    test_b2a_bit<int64_t>(test_size, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_b2a_bit<__int128_t>(test_size, engine);
#endif
    single_cout("B2A Bit Conversion...OK");

#ifdef USE_DALSKOV_FANTASTIC_FOUR
    test_b2a<int8_t>(100, engine);
    test_b2a<int32_t>(100, engine);
    test_b2a<int64_t>(100, engine);
#ifndef MPC_PROTOCOL_SPDZ_2K_NPC
    test_b2a<__int128_t>(100, engine);
#endif
    single_cout("B2A Conversion...OK");
#endif

// #if defined(MPC_PROTOCOL_FANTASTIC_FOUR) && defined(USE_DALSKOV_FANTASTIC_FOUR)
//     {
//         // Test Fantastic_4PC<GF2E> multiply_a
//         // Temporary test for now until we have full runtime integration or similar.
//         auto gf2e_proto = cdough::Fantastic_4PC<NTL::GF2E, std::vector<NTL::GF2E>, Vector<NTL::GF2E>,
//                                              EVector<NTL::GF2E>>(engine.getPartyID(), 0,
//                                                                  engine.comm0(), engine.rand0());
//         cdough::Vector<NTL::GF2E> x(test_size), y(test_size);

//         if (pID == 0) {
//             for (int i = 0; i < test_size; i++) {
//                 x[i] = NTL::random_GF2E();
//                 y[i] = NTL::random_GF2E();
//             }
//         }

//         auto sx = gf2e_proto.secret_share_a_internal(x, 0);
//         auto sy = gf2e_proto.secret_share_a_internal(y, 0);
//         EVector<NTL::GF2E> sz(sx.size());

//         gf2e_proto.multiply_a(sx, sy, sz);
//         auto z_open = gf2e_proto.unchecked_open_a(sz);
//         auto z_expected = x * y;

//         if (pID == 0) {
//             assert(z_open.same_as(z_expected));
//             single_cout("4PC GF2E multiply_a...OK");
//         }
//     }
// #endif

    engine.malicious_check();

    engine.print_statistics();

    return 0;
}