#pragma once

// =============================================================================
// A SQL oracle for the relational stage
//
// Lineage node `flagged_dx` pass 2 -- the window functions -- and the `umass` /
// `nonumass` per-system re-sequencing, executed by SQLite as SQL.
//
// Why this exists. Until now the relational stage was checked against exactly
// one oracle: SequencePlain (secure.h), a hand-written C++ mirror of the same
// upstream SQL. That oracle and the MPC implementation were written by the same
// person from the same reading of the same query, so a shared misreading gives
// two implementations that agree with each other and are both wrong. SQLite runs
// the query AS SQL, and is therefore independent of both by construction.
//
// Structurally this is the CryptDough analogue of orq's bench/queries/tpch/
// tpch_dbgen.h: an in-memory database populated from the same plaintext vectors
// that get secret-shared, queried at the end, and diffed against the MPC result.
//
// Scope, per tasks/0012: pass 2 and the re-sequencing only. Pass 1 (the
// row-local UPPER/LIKE flag parsing), the sisa_perct_cnt aggregates and
// conflict_list are out of scope here -- `newage` and the flags are inserted as
// DeriveFlagged computed them rather than recomputed in SQL.
//
// The union of both owners' halves exists only on the synthetic path. Nothing in
// a real deployment may construct this, for the same reason nothing may call
// SequencePlain: it needs what no single party holds.
// =============================================================================

#if defined(HAVE_SQLITE3)

#include <sqlite3.h>

#if SQLITE_VERSION_NUMBER < 3025000
#error "playground/sqlite_oracle.h needs SQLite >= 3.25 for window functions"
#endif

#include <iostream>
#include <string>

#include "./cohort.h"
#include "./etl.h"
#include "sequencing_sql.h"  // generated by cmake from playground/sql/sequencing.sql

namespace cdough::regression {

// Scope code as bound into the queries' ?1: 0 = any, 1 = UMass, 2 = non-UMass.
// Matches the data_source encoding, which is what lets `?1 = 0 OR data_source = ?1`
// serve all three scopes from one query.
inline int ScopeParam(SystemScope s) {
    switch (s) {
        case SystemScope::Any: return 0;
        case SystemScope::UMass: return 1;
        default: return 2;
    }
}

// =============================================================================
// class SqlOracle
//
// Owns an in-memory database holding the union of both owners' post-pass-1 rows,
// and runs the sequencing queries over it.
// =============================================================================
class SqlOracle {
  public:
    SqlOracle(const PlainFlagged& half_a, const PlainFlagged& half_b) {
        // ":memory:" explicitly. A NULL or empty filename creates a private
        // TEMPORARY database, which SQLite may spill to disk.
        Check(sqlite3_open(":memory:", &db_), "open");
        CreateSchema();
        Insert(half_a, 0);
        Insert(half_b, 1);
    }

    ~SqlOracle() { sqlite3_close(db_); }  // a no-op on nullptr

    SqlOracle(const SqlOracle&) = delete;
    SqlOracle& operator=(const SqlOracle&) = delete;

    bool ok() const { return db_ != nullptr && ok_; }

    // The corrected query -- what CryptDough implements. See
    // playground/sql/sequencing.sql for the transcription and the one deliberate
    // departure from the upstream text.
    PlainCohort Sequence(SystemScope scope) const {
        return Run(kSequencingSql, scope, "sequencing.sql");
    }

    // How many patients have more than one encounter on the same date. Not a
    // failure -- same-day revisits are real -- but a PASS on a run containing
    // none is no evidence that tie handling works, so the harness reports it.
    long CountSameDateTies() const {
        return Scalar(R"sql(
            SELECT COUNT(*) FROM (
                SELECT subject_id FROM flagged_dx
                GROUP BY subject_id, encounter_dt HAVING COUNT(*) > 1);
        )sql");
    }

  private:
    sqlite3* db_ = nullptr;
    mutable bool ok_ = true;

    void Check(int rc, const char* what) const {
        if (rc != SQLITE_OK && rc != SQLITE_DONE && rc != SQLITE_ROW) {
            ok_ = false;
            std::cerr << "SqlOracle: " << what << " failed: "
                      << (db_ ? sqlite3_errmsg(db_) : "could not open database") << std::endl;
        }
    }

    void Exec(const char* sql, const char* what) const {
        char* err = nullptr;
        if (sqlite3_exec(db_, sql, nullptr, nullptr, &err) != SQLITE_OK) {
            ok_ = false;
            std::cerr << "SqlOracle: " << what << " failed: " << (err ? err : "?") << std::endl;
            sqlite3_free(err);
        }
    }

    void CreateSchema() {
        // Deliberately NO primary key and NO unique index on
        // (subject_id, encounter_dt): roughly 1.5% of patients legitimately have
        // two encounters on one date, and a constraint would silently drop or
        // reject them -- destroying exactly the rows that exercise tie handling.
        Exec(R"sql(
            CREATE TABLE flagged_dx (
                owner        INTEGER NOT NULL,   -- 0 = A, 1 = B
                rid          INTEGER NOT NULL,   -- row index within that owner's half
                subject_id   INTEGER NOT NULL,
                encounter_dt INTEGER NOT NULL,   -- days from the public epoch
                data_source  INTEGER NOT NULL,   -- 1 = UMass, 2 = non-UMass
                newage       INTEGER NOT NULL,
                gender       INTEGER NOT NULL,
                hispanic     INTEGER NOT NULL,
                sisa         INTEGER NOT NULL,   -- suicide_acutecare_icd_narrow
                sa           INTEGER NOT NULL    -- sa_icd_narrow
            );
            CREATE INDEX ix_flagged ON flagged_dx (subject_id, encounter_dt);
        )sql",
             "CREATE TABLE");
    }

    // One owner's half. Called twice; never a UNION, which would dedupe the
    // same-date duplicates the tie handling exists to get right.
    void Insert(const PlainFlagged& f, long owner) {
        Exec("BEGIN TRANSACTION;", "BEGIN");
        static const char* kInsert =
            "INSERT INTO flagged_dx (owner, rid, subject_id, encounter_dt, data_source,"
            " newage, gender, hispanic, sisa, sa) VALUES (?,?,?,?,?,?,?,?,?,?);";
        sqlite3_stmt* stmt = nullptr;
        if (sqlite3_prepare_v2(db_, kInsert, -1, &stmt, nullptr) != SQLITE_OK) {
            Check(SQLITE_ERROR, "prepare INSERT");
            return;
        }
        for (size_t i = 0; i < f.rows(); ++i) {
            // int64 throughout: DataType is int64_t, and sqlite3_bind_int would
            // truncate silently.
            sqlite3_bind_int64(stmt, 1, owner);
            sqlite3_bind_int64(stmt, 2, static_cast<sqlite3_int64>(i));
            sqlite3_bind_int64(stmt, 3, f.subject_id[i]);
            sqlite3_bind_int64(stmt, 4, f.encounter_dt[i]);
            sqlite3_bind_int64(stmt, 5, f.data_source[i]);
            sqlite3_bind_int64(stmt, 6, f.newage[i]);
            sqlite3_bind_int64(stmt, 7, f.gender[i]);
            sqlite3_bind_int64(stmt, 8, f.hispanic[i]);
            sqlite3_bind_int64(stmt, 9, f.suicide_acutecare_icd_narrow[i]);
            sqlite3_bind_int64(stmt, 10, f.sa_icd_narrow_pcc[i]);
            if (sqlite3_step(stmt) != SQLITE_DONE) Check(SQLITE_ERROR, "INSERT");
            sqlite3_reset(stmt);
        }
        sqlite3_finalize(stmt);
        Exec("COMMIT;", "COMMIT");
    }

    long Scalar(const char* sql) const {
        sqlite3_stmt* stmt = nullptr;
        if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) != SQLITE_OK) {
            Check(SQLITE_ERROR, "prepare scalar query");
            return -1;
        }
        long out = -1;
        if (sqlite3_step(stmt) == SQLITE_ROW)
            out = static_cast<long>(sqlite3_column_int64(stmt, 0));
        else
            Check(SQLITE_ERROR, "step scalar query");
        sqlite3_finalize(stmt);
        return out;
    }

    // Column order is fixed by the SELECT list in playground/sql/sequencing.sql,
    // and scripts/testing/validate_mpc_analysis.py reads the same order.
    enum Col {
        kSubjectId = 0, kEncounterDt, kNewage, kGender, kHispanic,
        kIndexVisit, kVisitNum, kFinalVisit, kFuMonth, kDataSource, kSisa, kSa
    };

    PlainCohort Run(const char* sql, SystemScope scope, const char* what) const {
        PlainCohort c;
        c.scope = scope;
        sqlite3_stmt* stmt = nullptr;
        if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) != SQLITE_OK) {
            Check(SQLITE_ERROR, what);
            return c;
        }
        sqlite3_bind_int64(stmt, 1, ScopeParam(scope));

        int rc = sqlite3_step(stmt);
        while (rc == SQLITE_ROW) {
            auto col = [&](int i) {
                return static_cast<DataType>(sqlite3_column_int64(stmt, i));
            };
            c.subject_id.push_back(col(kSubjectId));
            c.encounter_dt.push_back(col(kEncounterDt));
            c.newage.push_back(col(kNewage));
            c.gender.push_back(col(kGender));
            c.hispanic.push_back(col(kHispanic));
            c.index_visit.push_back(col(kIndexVisit));
            c.visit_num.push_back(col(kVisitNum));
            c.final_visit.push_back(col(kFinalVisit));

            // A genuine SQL NULL, translated to the pipeline's separate
            // presence column. The SQL text stays faithful to upstream; the
            // 0/1 encoding is CryptDough's, because MPC has no NULL.
            const bool is_null = sqlite3_column_type(stmt, kFuMonth) == SQLITE_NULL;
            c.fu_month.push_back(is_null ? 0 : col(kFuMonth));
            c.fu_month_present.push_back(is_null ? 0 : 1);

            c.data_source.push_back(col(kDataSource));
            c.sisa.push_back(col(kSisa));
            c.sa.push_back(col(kSa));
            rc = sqlite3_step(stmt);
        }
        if (rc != SQLITE_DONE) Check(SQLITE_ERROR, what);
        sqlite3_finalize(stmt);
        return c;
    }
};

}  // namespace cdough::regression

#endif  // HAVE_SQLITE3
