// Assertion-based tests for cdough::regression::logistic in
// playground/library/regression.h -- the fixed-effects binary logit added by
// semantic task 0019, together with its Wald inference layer.
//
// WHY THIS LAYER IS THE ONE THAT MOST NEEDS A TEST. The inference chain
//
//     X' W X / n  ->  NewtonSchulzInverse  ->  covariance  ->  SecureSqrt
//                 ->  standard errors      ->  Wald z      ->  NormalCdf
//                 ->  p-value
//
// composes six approximate operators, and its output is a p-value -- a number
// someone will read as evidence. Every intermediate is plausible-looking: a
// covariance matrix of the right shape, positive standard errors, z statistics
// of the right order. None of it announces an error. The whole chain is checked
// here against a plaintext reference computed with exact linear algebra.
//
// The design also pins the cached X^T that `Dataset` builds in its constructor.
// That buffer serves BOTH orientations the namespace needs (row-major p x n is
// X^T; column-wise n x p is X itself, per semantic topic 0001 claim C-09), so
// if it were built wrongly, the gradient and the information matrix would both
// be wrong in a correlated way that a self-consistency check could not see.
//
// PRIVACY: a test, not a privacy demonstration. In particular `SeparationFlag`
// is opened here freely; in production it is one deliberate declassification.
//
// Run: mpirun -np 3 ./test_playground_fixed_effects

#include <algorithm>
#include <cmath>
#include <vector>

#include "cdough.h"

#include "../library/regression.h"
#include "test_util.h"

using namespace COMPILED_MPC_PROTOCOL_NAMESPACE;
using namespace cdough::debug;
using namespace cdough::service;
using namespace cdough::regression;
using namespace playground_test;

namespace {

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------
// Forty observations on an intercept plus two covariates. The size is set by the
// inference chain rather than by the likelihood: NewtonSchulzInverse needs an
// O(1)-scaled, well-conditioned operand, and X'WX/n only becomes that once there
// are enough rows for the averages to settle. Forty is comfortably past that and
// still runs in seconds.
//
// The covariates are generated by a closed-form rule rather than an RNG so that
// the fixture is identical on every party and in every run -- a seeded RNG would
// also be reproducible, but this way the reference needs no RNG at all.
//
// SCALING IS A PRECONDITION. `plain-lr.cpp` says it plainly: fixed point at
// `precision` 16 has limited headroom and the information matrix must be
// O(1)-scaled. The covariates below are on a standardized scale for that reason,
// not for tidiness.

constexpr std::size_t kNumObs = 40;
constexpr std::size_t kNumFixed = 3;  // intercept + 2 covariates
constexpr std::size_t kNumPoints = 2;

// The last two rows are PADDING (mask 0) and carry deliberately large values, so
// that a mask applied in the wrong place corrupts the aggregates visibly rather
// than subtly.
constexpr std::size_t kNumPadded = 2;

std::vector<double> MakeDesign() {
    std::vector<double> design(kNumObs * kNumFixed, 0.0);
    for (std::size_t i = 0; i < kNumObs; ++i) {
        const bool padded = i >= kNumObs - kNumPadded;
        design[i * kNumFixed + 0] = 1.0;
        if (padded) {
            design[i * kNumFixed + 1] = 7.0;
            design[i * kNumFixed + 2] = -8.0;
            continue;
        }
        design[i * kNumFixed + 1] = 0.5 * (static_cast<double>(i % 5) - 2.0);
        design[i * kNumFixed + 2] = 0.3 * (static_cast<double>(i % 7) - 3.0);
    }
    return design;
}

std::vector<double> MakeOutcome() {
    std::vector<double> outcome(kNumObs, 0.0);
    for (std::size_t i = 0; i < kNumObs; ++i) {
        outcome[i] = ((i * 7) % 11) < 5 ? 1.0 : 0.0;
    }
    return outcome;
}

std::vector<double> MakeMask() {
    std::vector<double> mask(kNumObs, 1.0);
    for (std::size_t i = kNumObs - kNumPadded; i < kNumObs; ++i) {
        mask[i] = 0.0;
    }
    return mask;
}

// Where the operators are evaluated. Modest, so that the linear predictors stay
// well inside the Exp clamp and the weights p(1-p) stay away from zero -- both
// conditions the inference layer needs and neither of which it checks.
const std::vector<double> kBeta = {0.20, 0.50, -0.30};
const std::vector<double> kSecondBeta = {-0.10, 0.25, 0.40};

constexpr double kZCritical = 1.96;

// ---------------------------------------------------------------------------
// Tolerances
// ---------------------------------------------------------------------------
//
// CALIBRATION. Each bound below was first derived a priori (from the 1.526e-5
// fixed-point resolution, from a figure measured by
// `playground/secure-logistic-regression.cpp` and recorded in semantic task
// 0019, or from an error-composition argument), then TIGHTENED once against the
// measured worst error, which is quoted beside it. The ratio is kept at roughly
// 5x to 15x: close enough that a real regression trips it, loose enough to
// survive a different build configuration.
//
// The measurements come from the 3PC build (PROTOCOL=3, DEFAULT_BITWIDTH=32,
// TRIPLES=DUMMY, DIVISION_CORRECTION=ON) on 2026-09-20, and were bit-identical
// across four consecutive runs -- the truncation error in this configuration is
// deterministic, not sampled. That determinism is a property of THIS build and
// must not be assumed for TRIPLES=REAL or another protocol; the margins below
// exist partly to absorb that.
//
// No bound was ever widened to make a failing check pass.

constexpr double kExactish = 4.0 * kResolution;  // ~6.1e-5

// The negative log-likelihood sums 38 unmasked terms, each a LogOnePlusExp
// (measured ~1.8e-4) plus a product. 38 * 2e-4 ~ 8e-3 if the errors aligned;
// they are not systematically signed, so this is a conservative bound.
constexpr double kNegLogLikTolerance = 1.5e-2;  // absolute; measured worst 4.90e-03 -- left as derived

// The ridge penalty is two multiplies and a sum.
constexpr double kPenaltyTolerance = 1.0e-4;  // absolute; measured worst 9.00e-06

// The analytic gradient: one Sigmoid over n elements, then a matmul contracting
// over n = 40. The contraction is where the error accumulates.
constexpr double kGradientTolerance = 3.0e-3;  // absolute; measured worst 6.25e-04

// X'WX/n. Same contraction, with the weights costing one more Sigmoid and two
// multiplies per row.
constexpr double kInformationTolerance = 2.0e-4;  // absolute; measured worst 1.95e-05

// The covariance inverts a matrix whose entries are O(0.2) and whose inverse is
// therefore O(5), so the inverse's absolute error is the operator's noise floor
// amplified by the scale of the answer. Relative is the only sensible mode here.
constexpr double kCovarianceTolerance = 1.0e-3;  // relative; measured worst 3.53e-05

// Standard errors take a square root, which halves relative error, but add
// SecureSqrt's own composed Exp-of-Log error (~4.7e-4 relative, measured).
constexpr double kStandardErrorTolerance = 1.0e-3;  // relative; measured worst 9.33e-05

// The Wald statistic is one division of two quantities each carrying the above.
constexpr double kWaldTolerance = 5.0e-4;  // relative; measured worst 1.03e-05

// Odds ratios exponentiate beta +- 1.96 se, so the standard error's relative
// error is multiplied by roughly 1.96 * se before the exponential.
constexpr double kOddsRatioTolerance = 3.0e-3;  // relative; measured worst 3.22e-04

// ---------------------------------------------------------------------------
// Plaintext mirror
// ---------------------------------------------------------------------------

std::vector<double> PlainLinearPredictor(const std::vector<double>& design,
                                         const std::vector<double>& beta) {
    std::vector<double> eta(kNumObs, 0.0);
    for (std::size_t i = 0; i < kNumObs; ++i) {
        double total = 0.0;
        for (std::size_t j = 0; j < kNumFixed; ++j) {
            total += design[i * kNumFixed + j] * beta[j];
        }
        eta[i] = total;
    }
    return eta;
}

double PlainNegLogLik(const std::vector<double>& design, const std::vector<double>& outcome,
                      const std::vector<double>& mask, const std::vector<double>& beta) {
    const std::vector<double> eta = PlainLinearPredictor(design, beta);
    double total = 0.0;
    for (std::size_t i = 0; i < kNumObs; ++i) {
        total += mask[i] * (RefLogOnePlusExp(eta[i]) - outcome[i] * eta[i]);
    }
    return total;
}

// lambda * sum_{j >= 1} beta_j^2, intercept excluded.
double PlainL2Penalty(const std::vector<double>& beta, double lambda) {
    double total = 0.0;
    for (std::size_t j = 1; j < kNumFixed; ++j) {
        total += beta[j] * beta[j];
    }
    return lambda * total;
}

std::vector<double> PlainGradient(const std::vector<double>& design,
                                 const std::vector<double>& outcome,
                                 const std::vector<double>& mask,
                                 const std::vector<double>& beta, double lambda) {
    const std::vector<double> eta = PlainLinearPredictor(design, beta);
    std::vector<double> gradient(kNumFixed, 0.0);
    for (std::size_t i = 0; i < kNumObs; ++i) {
        const double residual = mask[i] * (RefSigmoid(eta[i]) - outcome[i]);
        for (std::size_t j = 0; j < kNumFixed; ++j) {
            gradient[j] += design[i * kNumFixed + j] * residual;
        }
    }
    for (std::size_t j = 1; j < kNumFixed; ++j) {
        gradient[j] += 2.0 * lambda * beta[j];
    }
    return gradient;
}

// X' W X / n, with W = diag(mask_i * p_i (1 - p_i)).
//
// NOTE the divisor: the operator divides by `rows`, the PADDED width, not by the
// number of real observations. That is the operator's behaviour and the mirror
// reproduces it rather than "correcting" it -- a reference that silently used
// the real count would make a correct operator look wrong.
std::vector<double> PlainInformationOverN(const std::vector<double>& design,
                                          const std::vector<double>& mask,
                                          const std::vector<double>& beta) {
    const std::vector<double> eta = PlainLinearPredictor(design, beta);
    std::vector<double> information(kNumFixed * kNumFixed, 0.0);
    for (std::size_t i = 0; i < kNumObs; ++i) {
        const double probability = RefSigmoid(eta[i]);
        const double weight = mask[i] * probability * (1.0 - probability);
        for (std::size_t j = 0; j < kNumFixed; ++j) {
            for (std::size_t k = 0; k < kNumFixed; ++k) {
                information[j * kNumFixed + k] +=
                    design[i * kNumFixed + j] * weight * design[i * kNumFixed + k];
            }
        }
    }
    // Mirror the operator's rounded reciprocal exactly.
    const double inverse_n = RoundTrip(1.0 / static_cast<double>(kNumObs));
    for (double& entry : information) {
        entry *= inverse_n;
    }
    return information;
}

// ---------------------------------------------------------------------------
// Shared fixture
// ---------------------------------------------------------------------------

struct Fixture {
    logistic::Dataset data;
    std::vector<double> design;
    std::vector<double> outcome;
    std::vector<double> mask;
    std::vector<double> beta;
};

Fixture MakeFixture(EngineRef engine) {
    const std::vector<double> design = MakeDesign();
    const std::vector<double> outcome = MakeOutcome();
    const std::vector<double> mask = MakeMask();

    return Fixture{logistic::Dataset(ShareVector(design, engine), ShareVector(outcome, engine),
                                     ShareVector(mask, engine), kNumObs, kNumFixed),
                   RoundTrip(design), RoundTrip(outcome), RoundTrip(mask), RoundTrip(kBeta)};
}

// ---------------------------------------------------------------------------
// Dataset, including the cached transpose
// ---------------------------------------------------------------------------
void TestDataset(EngineRef engine) {
    Section("logistic::Dataset", engine);

    Fixture fixture = MakeFixture(engine);

    assert(fixture.data.num_obs() == kNumObs);
    assert(fixture.data.num_fixed() == kNumFixed);

    // The cached X^T is the operator's own claim: a p x n row-major buffer that
    // is simultaneously usable as a column-wise n x p view of X. Checking it
    // against an explicit transpose is what makes the claim falsifiable.
    CheckClose("Dataset caches X^T", OpenVector(fixture.data.xt_data),
               RefTranspose(fixture.design, kNumObs, kNumFixed), kExactish, engine);
}

// ---------------------------------------------------------------------------
// ClampNewtonStep
// ---------------------------------------------------------------------------
void TestClampNewtonStep(EngineRef engine) {
    Section("ClampNewtonStep", engine);

    const double bound = static_cast<double>(kMaxNewtonStep);
    const std::vector<double> inputs = {-9.0, -4.0, -3.9, -0.5, 0.0, 0.5, 3.9, 4.0, 12.5};

    std::vector<double> expected;
    expected.reserve(inputs.size());
    for (const double value : inputs) {
        expected.push_back(std::max(-bound, std::min(bound, RoundTrip(value))));
    }

    AV shared = ShareVector(inputs, engine);
    CheckClose("ClampNewtonStep", OpenVector(ClampNewtonStep(shared)), expected, kExactish,
               engine, ErrorMode::Absolute, inputs);
}

// ---------------------------------------------------------------------------
// The objective
// ---------------------------------------------------------------------------
void TestNegLogLik(EngineRef engine) {
    Section("NegLogLikBatched / L2Penalty / PenalizedNegLogLikBatched", engine);

    Fixture fixture = MakeFixture(engine);

    // Two parameter points at once, which is how the line search calls it.
    std::vector<double> packed(kBeta);
    packed.insert(packed.end(), kSecondBeta.begin(), kSecondBeta.end());
    const std::vector<double> packed_rounded = RoundTrip(packed);

    const std::vector<double> first(packed_rounded.begin(), packed_rounded.begin() + kNumFixed);
    const std::vector<double> second(packed_rounded.begin() + kNumFixed, packed_rounded.end());

    const std::vector<double> expected = {
        PlainNegLogLik(fixture.design, fixture.outcome, fixture.mask, first),
        PlainNegLogLik(fixture.design, fixture.outcome, fixture.mask, second)};

    AV beta = ShareVector(packed, engine);
    CheckClose("NegLogLikBatched (K = 2)",
               OpenVector(logistic::NegLogLikBatched(fixture.data, beta, kNumPoints)), expected,
               kNegLogLikTolerance, engine);

    // K = 1, the shape the analytic-gradient path and any single evaluation use.
    AV single = ShareVector(first, engine);
    CheckClose("NegLogLikBatched (K = 1)",
               OpenVector(logistic::NegLogLikBatched(fixture.data, single, 1)), {expected[0]},
               kNegLogLikTolerance, engine);

    // ---- L2Penalty ----
    // lambda == 0 must return exact zeros, not something small: the namespace
    // defaults to no penalty precisely so that these estimates match a PROC
    // GLIMMIX fit, and a penalty that leaked in at 1e-9 would still be a penalty.
    AV zero_penalty = logistic::L2Penalty(beta, kNumPoints, kNumFixed, 0);
    const std::vector<double> zero_opened = OpenVector(zero_penalty);
    for (const double value : zero_opened) {
        assert(value == 0.0 && "L2Penalty with lambda == 0 returned a non-zero value");
    }
    Note("L2Penalty(lambda = 0) is exactly zero, as the GLIMMIX-matching default requires",
         engine);

    const double lambda = 0.25;
    const DataType lambda_scaled = static_cast<DataType>(std::llround(lambda * scale));
    const double lambda_rounded = RoundTrip(lambda);

    const std::vector<double> penalty_expected = {PlainL2Penalty(first, lambda_rounded),
                                                  PlainL2Penalty(second, lambda_rounded)};
    CheckClose("L2Penalty (intercept excluded)",
               OpenVector(logistic::L2Penalty(beta, kNumPoints, kNumFixed, lambda_scaled)),
               penalty_expected, kPenaltyTolerance, engine);

    // The intercept exclusion, checked directly: a point whose ONLY non-zero
    // coordinate is the intercept must incur no penalty at all. A penalty that
    // included column 0 would shrink the intercept toward zero, which is a
    // modelling error rather than a numerical one and would never show up as a
    // tolerance failure elsewhere.
    const std::vector<double> intercept_only = {1.5, 0.0, 0.0};
    AV intercept_shared = ShareVector(intercept_only, engine);
    const std::vector<double> intercept_penalty =
        OpenVector(logistic::L2Penalty(intercept_shared, 1, kNumFixed, lambda_scaled));
    assert(intercept_penalty[0] == 0.0 && "L2Penalty penalized the intercept");
    Note("L2Penalty leaves a pure-intercept point unpenalized", engine);

    // ---- PenalizedNegLogLikBatched = NegLogLik + penalty ----
    std::vector<double> penalized_expected(kNumPoints);
    for (std::size_t k = 0; k < kNumPoints; ++k) {
        penalized_expected[k] = expected[k] + penalty_expected[k];
    }
    CheckClose("PenalizedNegLogLikBatched",
               OpenVector(logistic::PenalizedNegLogLikBatched(fixture.data, beta, kNumPoints,
                                                              lambda_scaled)),
               penalized_expected, kNegLogLikTolerance, engine);
}

// ---------------------------------------------------------------------------
// LogisticGradient
// ---------------------------------------------------------------------------
void TestGradient(EngineRef engine) {
    Section("LogisticGradient", engine);

    Fixture fixture = MakeFixture(engine);
    AV beta = ShareVector(fixture.beta, engine);

    CheckClose("LogisticGradient (lambda = 0)",
               OpenVector(logistic::LogisticGradient(fixture.data, beta)),
               PlainGradient(fixture.design, fixture.outcome, fixture.mask, fixture.beta, 0.0),
               kGradientTolerance, engine);

    const double lambda = 0.25;
    const DataType lambda_scaled = static_cast<DataType>(std::llround(lambda * scale));
    CheckClose("LogisticGradient (ridge)",
               OpenVector(logistic::LogisticGradient(fixture.data, beta, lambda_scaled)),
               PlainGradient(fixture.design, fixture.outcome, fixture.mask, fixture.beta,
                             RoundTrip(lambda)),
               kGradientTolerance, engine);
}

// ---------------------------------------------------------------------------
// The Wald inference chain
// ---------------------------------------------------------------------------
void TestInference(EngineRef engine) {
    Section("ObservedInformationOverN / Covariance / StandardErrors / Wald", engine);

    Fixture fixture = MakeFixture(engine);
    AV beta = ShareVector(fixture.beta, engine);

    // ---- X' W X / n ----
    const std::vector<double> information_expected =
        PlainInformationOverN(fixture.design, fixture.mask, fixture.beta);
    CheckClose("ObservedInformationOverN",
               OpenMatrix(logistic::ObservedInformationOverN(fixture.data, beta)),
               information_expected, kInformationTolerance, engine);

    // ---- covariance = (X' W X)^-1 ----
    // (A/n)^-1 = n A^-1, so the operator inverts the normalized matrix and
    // rescales; the mirror does the same, with the same rounded 1/n.
    std::vector<double> covariance_expected = information_expected;
    const bool invertible = RefInvert(covariance_expected, kNumFixed);
    assert(invertible && "test fixture information matrix is singular");
    const double inverse_n = RoundTrip(1.0 / static_cast<double>(kNumObs));
    for (double& entry : covariance_expected) {
        entry *= inverse_n;
    }

    SMatrix covariance = logistic::Covariance(fixture.data, beta);
    CheckClose("Covariance", OpenMatrix(covariance), covariance_expected, kCovarianceTolerance,
               engine, ErrorMode::Relative);

    // ---- standard errors ----
    std::vector<double> standard_error_expected(kNumFixed);
    for (std::size_t j = 0; j < kNumFixed; ++j) {
        const double variance = covariance_expected[j * kNumFixed + j];
        assert(variance > 0.0 && "fixture covariance has a non-positive diagonal");
        standard_error_expected[j] = std::sqrt(variance);
    }

    AV standard_errors = logistic::StandardErrors(covariance);
    const std::vector<double> standard_error_actual = OpenVector(standard_errors);
    CheckClose("StandardErrors", standard_error_actual, standard_error_expected,
               kStandardErrorTolerance, engine, ErrorMode::Relative);

    // ---- Wald statistics ----
    // The reference uses the SECURE standard errors, not the plaintext ones.
    // That is deliberate: this check is of the division and the sign handling,
    // and folding in the standard errors' own error would test the previous
    // stage twice and this one not at all.
    std::vector<double> wald_expected(kNumFixed);
    for (std::size_t j = 0; j < kNumFixed; ++j) {
        wald_expected[j] = fixture.beta[j] / standard_error_actual[j];
    }

    AV wald = logistic::WaldStatistics(beta, standard_errors);
    const std::vector<double> wald_actual = OpenVector(wald);
    CheckClose("WaldStatistics", wald_actual, wald_expected, kWaldTolerance, engine,
               ErrorMode::Relative);

    // The sign path specifically. The operator divides |beta| and reattaches the
    // sign afterwards, because the non-restoring division circuit assumes a
    // non-negative numerator -- handing it a negative coefficient is undefined
    // behaviour inside the circuit, not merely a wrong answer. kBeta's third
    // coefficient is negative, so this is exercised above; assert it explicitly
    // so a future edit to the fixture cannot quietly remove the coverage.
    assert(fixture.beta[2] < 0.0 && "fixture must include a negative coefficient");
    assert(wald_actual[2] < 0.0 && "Wald statistic lost the sign of a negative coefficient");
    Note("negative-coefficient path exercised: beta[2] < 0 and z[2] < 0", engine);

    // ---- p-values ----
    // Held to the primitives' own tolerance rather than a looser one: the input
    // is the secure z, so the only new error is TwoSidedPValue's.
    std::vector<double> p_expected(kNumFixed);
    for (std::size_t j = 0; j < kNumFixed; ++j) {
        p_expected[j] = RefTwoSidedPValue(wald_actual[j]);
    }
    CheckClose("TwoSidedPValue(Wald z)", OpenVector(TwoSidedPValue(wald)), p_expected, 1.0e-3,
               engine, ErrorMode::Absolute);

    // ---- odds ratios ----
    std::vector<double> ratio_expected(kNumFixed);
    std::vector<double> lower_expected(kNumFixed);
    std::vector<double> upper_expected(kNumFixed);
    for (std::size_t j = 0; j < kNumFixed; ++j) {
        const double margin = RoundTrip(kZCritical) * standard_error_actual[j];
        ratio_expected[j] = std::exp(fixture.beta[j]);
        lower_expected[j] = std::exp(fixture.beta[j] - margin);
        upper_expected[j] = std::exp(fixture.beta[j] + margin);
    }

    logistic::OddsRatioEstimate odds = logistic::OddsRatio(beta, standard_errors, kZCritical);
    CheckClose("OddsRatio.ratio", OpenVector(odds.ratio), ratio_expected, kOddsRatioTolerance,
               engine, ErrorMode::Relative);
    CheckClose("OddsRatio.lower", OpenVector(odds.lower), lower_expected, kOddsRatioTolerance,
               engine, ErrorMode::Relative);
    CheckClose("OddsRatio.upper", OpenVector(odds.upper), upper_expected, kOddsRatioTolerance,
               engine, ErrorMode::Relative);

    // Ordering: lower < ratio < upper. Cheap, and independent of the values --
    // it would catch a sign swap in the margin that the relative checks above
    // could conceivably tolerate for a small standard error.
    const std::vector<double> ratio_actual = OpenVector(odds.ratio);
    const std::vector<double> lower_actual = OpenVector(odds.lower);
    const std::vector<double> upper_actual = OpenVector(odds.upper);
    for (std::size_t j = 0; j < kNumFixed; ++j) {
        assert(lower_actual[j] < ratio_actual[j] && "odds ratio lower limit is not below the point estimate");
        assert(ratio_actual[j] < upper_actual[j] && "odds ratio upper limit is not above the point estimate");
    }
    Note("odds-ratio limits bracket the point estimate for every coefficient", engine);
}

// ---------------------------------------------------------------------------
// SeparationFlag
// ---------------------------------------------------------------------------
// The flag is a single opened bit and the only safeguard against a fit that has
// been driven into the Exp clamp -- a failure the operator's own comment
// describes as "silent and looks exactly like success". Both outcomes are
// checked, because a flag that is always 0 would pass a one-sided test and
// protect nothing.
void TestSeparationFlag(EngineRef engine) {
    Section("SeparationFlag", engine);

    Fixture fixture = MakeFixture(engine);

    AV modest = ShareVector(fixture.beta, engine);
    CheckExactRaw("SeparationFlag clear at a modest beta",
                  OpenRaw(logistic::SeparationFlag(fixture.data, modest)), {0}, engine);

    // Large enough that some |eta| passes kMaxExpArg = 10. The largest covariate
    // magnitude among the real rows is 1.0, so a coefficient of 12 on it does it.
    const std::vector<double> separated = {0.0, 12.0, 0.0};
    AV extreme = ShareVector(separated, engine);
    CheckExactRaw("SeparationFlag set past the Exp clamp",
                  OpenRaw(logistic::SeparationFlag(fixture.data, extreme)), {1}, engine);

    // The bound is a parameter, so a tighter one must fire where the default
    // does not. This is what says the flag is actually comparing against the
    // bound rather than against a constant.
    const DataType tight_bound = static_cast<DataType>(std::llround(0.5 * scale));
    CheckExactRaw("SeparationFlag honours a tighter bound",
                  OpenRaw(logistic::SeparationFlag(fixture.data, modest, tight_bound)), {1},
                  engine);
}

}  // namespace

int main(int argc, char** argv) {
    EngineRef engine = cdough_init(argc, argv);

    if (engine.getPartyID() == 0) {
        std::cout << "\n########## regression.h :: logistic ##########\n"
                  << "observations = " << kNumObs << " (" << kNumPadded << " padded)"
                  << "   coefficients = " << kNumFixed << "   points = " << kNumPoints
                  << std::endl;
    }

    TestDataset(engine);
    TestClampNewtonStep(engine);
    TestNegLogLik(engine);
    TestGradient(engine);
    TestInference(engine);
    TestSeparationFlag(engine);

    if (engine.getPartyID() == 0) {
        std::cout << "\nlogistic: all checks passed" << std::endl;
    }

    return 0;
}
